### ISSUE TITLE
file "clip_data/" not found

### ISSUE THREAD

**Issue by RaisnnowLawrence** [YunxinLi/Multimodal-Context-Reasoning#4]
Hello.
Some missing files were found when i running the file "run_PMR_ModCR.py".
```
Traceback (most recent call last):
  File "run_PMR_ModCR.py", line 951, in <module>
    main()
  File "run_PMR_ModCR.py", line 861, in main
    train_dataset = PMR_ChunkAlign_Dataset_align_ensemble_T(tokenizer, gpt_tokenizer, roberta_tokenizer,
  File "/home/stormai/userfile/lizhengxue/WorkOnModCR/Multimodal-Context-Reasoning-main/Data/VCRChunkAlign.py", line 555, in __init__
    with open(clip_example_file, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'pmr_data/clip_data/train_p_ori-clip.jsonl'
```
How do I access these files (such as clip_data/) ?

**Comment by YunxinLi** [comment]
Hello, the clip_data file is useless in ModCR. You can remove the codes loading corresponding file(clip_data).
All data feature have benn uploaded to data_feature.zip: https://huggingface.co/YunxinLi/ModCR_checkpoints

**Comment by YunxinLi** [comment]
The image features of source images from PCR or VCR have been preprocessed by CLIP and they are stored in the data_feature.zip.
